### PR TITLE
t/350: It should be possible to use "dirty" third-party SVGs as the content of the IconView

### LINKED ISSUE #350: Poor SVG icon support in a ButtonView/IconView
I created a toolbar button. When trying to add an icon to it I found that it's really cumbersome. Whatever SVG I tried, it did not render correctly inside the toolbar.
I would expect to see there an SVG image scaled proportionally to the amount of space that is available for it. Instead, I can see just the small top left corner of it (most of the SVGs that I tried had size like 500x500).

The source of the issue lays in the `IconView`, which forces the following:
```
this.set( 'viewBox', '0 0 20 20' );
```

In order to fix my icon I had to set
```
button.iconView.set( 'viewBox', '0 0 128 128' );
```

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: It should be possible to use "dirty" third-party SVGs as the content of the IconView. Closes #350.

### CODE REVIEW

**Comment by Reinmar** [comment]
Can we have a manual test which proves that this PR fixes the issue?

**Comment by oleq** [comment]
Extended existing test in https://github.com/ckeditor/ckeditor5-ui/pull/352/commits/f6f893fac09b0b4f1895a0a4adc2284710aeeccc. Can you check this out, @Reinmar?

**Comment by Reinmar** [comment]
It certainly makes the manual test to pass. But it breaks CI: https://travis-ci.org/ckeditor/ckeditor5-ui/builds/315332565?utm_source=github_status&utm_medium=notification

**Comment by oleq** [comment]
It looks OK now.

**Pull request merged**
