### PR TITLE
Fix: Use proper translations used to prevent blurry icons in toolbar …

### LINKED ISSUE #340: Bug: Icons are fuzzy in Firefox
Fix fuzzy icons on Firefox as described in https://github.com/ckeditor/ckeditor5/issues/668.

### PR DESCRIPTION
**Pull request by jodator**
…on Firefox.

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Use proper translations used to prevent blurry icons in toolbar on Firefox. Closes #340. Closes ckeditor/ckeditor5#668.

---

### Additional information

* As discussed in https://github.com/ckeditor/ckeditor5/issues/668#issuecomment-344846429 I've changed some `transformY` to `transform3d` and added `will-change` where transformation is already applied.

### CODE REVIEW

**Comment by oleq** [comment]
The changes look good but I'll handle this PR after https://github.com/ckeditor/ckeditor5-ui/pull/339.

**Comment by jodator** [comment]
I've updated the solution to PostCSS. Works well with current Alignment (after fixing button.css in ui) and other toolbar buttons on Firefox:

selection_048

**Comment by Reinmar** [comment]
Can we merge this?

**Comment by Reinmar** [comment]
Works fine for me, so I'm merging it.

**Pull request merged**
