### PR TITLE
t/228: Clicking and dragging in a dropdown panel should not break the selection

### LINKED ISSUE #228: Misclicks on drop down panels cause selection to be lost
We had a ticket for it, but I can't find it at the moment. I can really often reproduce this issue:

may-10-2017 15-22-57

I think it's related to the issue we had in the past that when there's any dragstart+move sequence the selection is being lost. This is very important issue when you try to actually use the editor for real.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Clicking and dragging in a dropdown panel should not break the selection. Closes #228.

### CODE REVIEW

**Comment by oleq** [comment]
Although it fixes the issue I'm not quite sure if it isn't a little bit too much (too aggressive). 

What possible problems could we face (in the future) because of this fix? If we decided to keep something complex (e.g. a form in the dropdown), it would certainly disrupt it. OTOH, is `DropdownPanelView` the right component for such applications?

**Comment by oleq** [comment]
It turned out the `selectstart` event does the same trick but it's less aggressive, e.g. it doesn't break item focus in the dropdown list.

**Comment by Reinmar** [comment]
Couldn't this fix land in the dropdown panel? It'd handle all panels and that's kinda panels' issue because they display over the content. Similar problem may also apply to balloons but I never experienced it.

**Comment by oleq** [comment]
The fix is already in the `dropdownpanelview.js`.

**Comment by Reinmar** [comment]
The patch doesn't fix the issue in Safari.

**Comment by Reinmar** [comment]
And it's this kind of issue which should have a manual test.

**Comment by oleq** [comment]
I created a manual test for the issue.  

As for Safari, it doesn't need the fix at all. Although visually the selection is no longer highlighted in the browser after dropping, press Esc twice to go back to editable and you'll find out that the selection is restored properly.

**Comment by Reinmar** [comment]
Pity that in Safari the selection disappears for a while, but it indeed works fine. We can live with that for some time.

**Pull request merged**
