### PR TITLE
Views added to the ContextualBalloon should respect the position of the currently visible panel.

### LINKED ISSUE #185: Improve ContextualBalloon manual test
Follow-up: https://github.com/ckeditor/ckeditor5-ui/issues/134

After `ContextualBalloon` will be integrated with `Link` or `Image` and `ContextualToolbar` component will be introduced we can simplify `ContextualToolbar` manual test using above plugins/components.

### LINKED ISSUE #285: The link balloon does not respect the position of the ContexualToolbar
## Now is:

aug-03-2017 12-21-19

## Expected result:

aug-03-2017 12-28-25

### PR DESCRIPTION
**Pull request by oskarwrobel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Views added to the `ContextualBalloon` should respect the position of the currently visible panel. Closes #285. Closes #185.

### CODE REVIEW

**Comment by oleq** [comment]
This view causes a regression in the image UI.

## Expected
kapture 2017-08-07 at 11 46 49


## Actual

kapture 2017-08-07 at 11 45 45

**Comment by oskarwrobel** [comment]
This is very strange.

**Comment by oskarwrobel** [comment]
Something is wrong with image balloon in general. That's how it works on master now:

aug-07-2017 12-18-22

Disabled balloon stays visible when image lost focus.

**Comment by oskarwrobel** [comment]
> This view causes a regression in the image UI.

> Something is wrong with image balloon in general.

Both are fixed after merging: https://github.com/ckeditor/ckeditor5-ui/issues/281.

**Pull request merged**
