### PR TITLE
t/311: createListDropdown helper should use clickOutsideHandler

### LINKED ISSUE #311: createListDropdown helper should use clickOutsideHandler
ATM `createListDropdown` uses own custom click handling. It's redundant.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: The `createListDropdown` helper should use `clickOutsideHandler`. Closes #311.

### CODE REVIEW

**Comment by oleq** [comment]
self.r-: This change breaks this test 
https://github.com/ckeditor/ckeditor5-heading/blob/888f9571528f78720c231c19b2358fd5e02f7397/tests/heading.js#L93-L96 as the clickOutsideHandler references `view#element` before `Template.extend` in https://github.com/ckeditor/ckeditor5-heading/blob/master/src/heading.js#L98-L106.

Again, it's all about https://github.com/ckeditor/ckeditor5-ui/issues/262.

**Comment by oleq** [comment]
It turned out this code still won't work. 

It's because the `clickOutsideHandler` [requires a reference to `View#element` in its `contextElements`](https://github.com/ckeditor/ckeditor5-ui/pull/312/files#diff-87ab2335c9320fb35ff63d466896a203R78), which is not available in the `createListDropdown` helper because it returns an instance which is not rendered (yet). And it makes sense, because one might want to customize the instance even further so we cannot simply `render()` it in `createListDropdown`.

Possible solutions:
1. Implement `View#render` event fired after the view is rendered. Then: 
	```js
	function createListDropdown( ... ) {
		const dropdownView = createDropdown( ... );

		// ...

		dropdownView.on( 'render', () => {
			clickOutsideHandler( {
				emitter: dropdownView,
				activator: () => dropdownView.isOpen,
				callback: () => {
					dropdownView.isOpen = false;
				},
				contextElements: [ dropdownView.element ]
			} );
		} );

		// ...
	}
	```    
2. Allow `contextElements` defined as function, so it returns the value (`dropdownView.element`) on demand when the actual `mousedown` is fired and, obviously, the `dropdownView.element` already exists.

**Comment by Reinmar** [comment]
The `#render` event sound fine, as something you'd want anyway in some other place.

**Comment by Reinmar** [comment]
Actually, sorry – `#rendered` because it should be fired once the element is already available.

**Comment by oleq** [comment]
I decorated `View#render` method instead. Seems like the easiest solution.

**Comment by oleq** [comment]
Due to recent changes in the drop-down API, this PR became obsolete. Replaced by https://github.com/ckeditor/ckeditor5-ui/pull/353.

**Pull request closed without merging**
