### PR TITLE
t/119: New tooltip architecture

### PR DESCRIPTION
**Pull request by oleq**
Closes https://github.com/ckeditor/ckeditor5-ui/issues/119.
Closes https://github.com/ckeditor/ckeditor5-ui-default/issues/147.
Closes https://github.com/ckeditor/ckeditor5-ui-default/issues/148.
Closes https://github.com/ckeditor/ckeditor5-ui-default/issues/150.

### CODE REVIEW

**Comment by Reinmar** [comment]
Is it correct that tooltip isn't displayed for disabled buttons?

**Comment by oleq** [comment]
Yes. It's by design. In fact, I was wondering if this is correct but decided that less distraction is better. The button isn't available anyway. OTOH, I'm aware that this is a blow to the feature discoverability.

**Comment by Reinmar** [comment]
I think it's a bit strange when e.g. you have disabled undo or redo buttons (redo is disabled most of the time, while undo isn't).

**Comment by oleq** [comment]
Let's find out what people will say. It's a single line of CSS to re–enable them.

**Comment by fredck** [comment]
Please re-enable them. This is the default behavior with "title" and users must have a clue on what is that disabled button about.

**Pull request merged**
